# Generated by Django 2.0.6 on 2019-03-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMakerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=200)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('ProfilePicture', models.URLField()),
                ('UserLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PictureOfMeal', models.URLField()),
                ('NameOfMeal', models.CharField(max_length=100)),
                ('IngredientsForMeal', models.CharField(max_length=500)),
                ('DirectionsForMeal', models.TextField(max_length=500)),
                ('DateCreated', models.DateField(default=django.utils.timezone.now)),
                ('CreatorOfRecipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RecipeRecordingApp.RecipeMakerModel')),
            ],
        ),
    ]
