# Generated by Django 2.0.6 on 2019-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeRecordingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemakermodel',
            name='ProfilePicture',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='PictureOfMeal',
            field=models.URLField(max_length=500),
        ),
    ]
